### ISSUE TITLE
JSCS-Formatter Error: module.js:338

### ISSUE THREAD

**Issue by janagaprobert** [TheSavior/SublimeJSCSFormatter#33] opened 2015-06-04 12:24 UTC
I can't get it and need help for this error.
Error: module.js:338
 throw err;
error: cannot find module 'C:\Users\Robert'
  at function.Module._resolveFilename (module.js:336:15)
  at function.Module._load(module.js:278:25)
  at function.Module.runMain(module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3

**Comment by mrjoelkemp** [comment] 2015-06-04 13:29
Duplicate of https://github.com/TheSavior/SublimeJSCSFormatter/issues/14.

**Closed as completed** 2015-06-04 16:08 UTC
