### ISSUE TITLE
Unexpected Token ILLEGAL - Error message under Windows

### ISSUE THREAD

**Issue by brakmic** [TheSavior/SublimeJSCSFormatter#12] opened 2015-03-31 15:28 UTC
Each time I try to use the plugin the following message appears. I suppose the culprit is the _backtick_ in plugin's code.

``` python
Unexpected error(<class 'Exception'>): Error: C:\Users\Harris\AppData\Roaming\npm\jscs:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
error: Error: C:\Users\Harris\AppData\Roaming\npm\jscs:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by elicwhite** [comment] 2015-03-31 16:15
Interesting. it looks like it is failing inside of JSCS, not inside of the JSCS-Formatter sublime plugin. When you run on the command line `jscs --version`, what do you get?

Are you using the SublimeLinter-JSCS package as well? Does that work for you?

**Comment by brakmic** [comment] 2015-03-31 16:15
1.12.0
Yes, I do use the SublimeLinter.JSCS package. The linting works properly.

**Comment by elicwhite** [comment] 2015-03-31 16:34
Weird. The error is inside of `node-jscs/node_modules/minimatch/node_modules/brace-expansion/test/generate.sh` `brace-expansion` seems to handle things like this:

```
expand('file-{a,b,c}.jpg')
// => ['file-a.jpg', 'file-b.jpg', 'file-c.jpg'] 
```

I'm kinda grasping at straws here, but is there any chance that the file name or path of the file that you are running this on contains curly braces?

**Comment by brakmic** [comment] 2015-03-31 16:36
I have no curly braces in my path. It's a rather "typical" Visual Studio project with some JavaScript in it. Some _node_modules_ are there but that's all. Nothing exceptional, as far as I can see.

**Comment by elicwhite** [comment] 2015-03-31 16:40
Hmm. I don't know if I can really debug this one much further. If you happen to figure something out, I'd love to hear some ideas, or even a pull request. ;)

Thanks for reporting this, sorry I couldn't fix it for you right away.

**Comment by varemenos** [comment] 2015-03-31 16:42
A colleague of mine who is also using Windows has the same issue

**Comment by brakmic** [comment] 2015-03-31 16:42
No problem. Thanks for your effort regarding the plugin. I'll try to figure out where the error may be located.

Regads,
Harris

**Comment by brakmic** [comment] 2015-03-31 16:46
Maybe this thread from GitHub can help us in some way. 

The story is as follows: 

Many node packages on Windows ship *.cmd versions of their original shell scripts. When you try to use the original package you sometimes get weird errors. But when you resort to *.cmd versions the tools (mostly) work.

Ok, I know, this is far from being a _waterproof_ solution but maybe it can help us locate the problem more precisely?

https://github.com/iceddev/frozen-dev-boilerplate/issues/2

**Comment by brakmic** [comment] 2015-03-31 16:54
Also, I'd recommend to check if the plugin tries to use any modules from _node_module/.bin/_ subdirectory. In some other case I had to suppress this behavior and relocate the calls to global npm-paths and *.cmd scripts.

**Comment by elicwhite** [comment] 2015-03-31 23:42
@mrjoelkemp Have you seen anything like this related to JSCS on windows?

**Comment by mrjoelkemp** [comment] 2015-03-31 23:48
That's es6 code. You may need to allow users to set the esnext flag.

**Comment by elicwhite** [comment] 2015-03-31 23:52
They can set es6 from the `.jscsrc` file correct? Also, I'm not sure this is es6 code. I know backticks are es6, but I think that is just a figment of the error log. There are other reports on the web about this issue with the resolution seeming to be to not include `./node_modules/.bin` in the npm scripts. I'm pretty sure that isn't the issue here though. :-P

**Comment by mrjoelkemp** [comment] 2015-03-31 23:58
@brakmic Any chance you could run the plugin on a file that doesn't contain es6 code? 

Also what does your jscsrc file look like? Do you have the esnext flag set?

**Comment by brakmic** [comment] 2015-04-01 08:21
Hi @mrjoelkemp,

When I run the plugin on an ES5 file I get another error:

``` javascript
Using node.js path on 'windows': C:/bin/nodejs/node.exe
Using jscs path on 'windows': C:/Users/Harris/AppData/Roaming/npm/jscs
Unexpected error(<class 'BrokenPipeError'>): [Errno 32] Broken pipe
error: [Errno 32] Broken pipe
```

Interestingly, the same problems appear when I run it on one of my _Jasmine_ specs. I get the same _illegal-path error_. But my Specs are written in plain old ES5 javascript. :smile: 

I've also put the esnext flag into my _.jscsrc_ and still get the same error regarding the illegal token:

Here's my .jscsrc

``` javascript
{
  "preset": "google",
    "fileExtensions": [ ".js", "jscs" ],

    "requireParenthesesAroundIIFE": true,
    "maximumLineLength": 120,
    "validateLineBreaks": "LF",
    "validateIndentation": 4,
    "esnext": true,

    "disallowKeywords": ["with"],
    "disallowSpacesInsideObjectBrackets": null,
    "disallowImplicitTypeConversion": ["string"],

    "safeContextKeyword": "_this",
  "excludeFiles": ["node_modules/**"]
}
```

**Comment by mrjoelkemp** [comment] 2015-04-01 08:40
Thanks for the details. Out of curiosity, what version of node are you using?

**Comment by brakmic** [comment] 2015-04-01 08:42
v0.12.0

**Comment by varemenos** [comment] 2015-04-01 08:45
my colleague is using v0.10.24, his code was "ES5 complaint"

**Comment by mrjoelkemp** [comment] 2015-04-01 08:46
Thanks again. You both are able to use jscs successfully  outside the plugin, correct? Thanks for your help in debugging this issue.

**Comment by varemenos** [comment] 2015-04-01 08:47
Yep, `jscs --fix` works just fine
edit: the linter works fine too

**Comment by brakmic** [comment] 2015-04-01 09:24
Yes, SublimeLinter-jscs works properly.

**Comment by mrjoelkemp** [comment] 2015-04-01 09:34
Thanks. I'll try debugging this on a windows machine. Will report back with any findings.

**Comment by elicwhite** [comment] 2015-04-01 09:56
@mrjoelkemp, thank you so much for your help with these windows issues. Having a windows machine with your JSCS + Sublime Packages experience makes you invaluable here. I hope you are able to figure out what is happening here, I have no idea. haha

**Comment by mrjoelkemp** [comment] 2015-04-01 11:22
I was able to reproduce the error on a windows machine.

I think the problem is that the command being run as `path/to/node path/to/jscs` instead of just `jscs`. If the user has globally installed jscs, shelling out that command should work (though I remember having PATH troubles with this in OSX in the past).

I'll pull the plugin's source down onto the windows machine and edit the source appropriately to see what the proper fix is.

**Comment by brakmic** [comment] 2015-04-01 11:30
I changed the path to "jscs" and now get this error:

``` javascript
Using jscs path on 'windows': jscs.cmd
Unexpected error(<class 'BrokenPipeError'>): [Errno 32] Broken pipe
error: [Errno 32] Broken pipe
reloading Packages/User/JSCS-Formatter.sublime-settings
Using node.js path on 'windows': C:/bin/nodejs/node.exe
Using jscs path on 'windows': jscs
Unexpected error(<class 'BrokenPipeError'>): [Errno 32] Broken pipe
error: [Errno 32] Broken pipe
```

**Comment by mrjoelkemp** [comment] 2015-04-01 11:44
Yeah @brakmic, that's not enough. That will give you `node jscs` instead of just `jscs` (what should work). Removing the use of `node` (either for only windows or globally) requires changes to the plugin.

Sorry for the inconvenience here.

**Comment by brakmic** [comment] 2015-04-01 11:45
No problem, @mrjoelkemp. This is really not a problem but just a bug hunt. 
The real problem is, for example, the DDOS attack against GitHub :wink: 

Thanks!

**Comment by busches** [comment] 2015-04-01 16:21
For what it's worth, changing my path to reference the jscs executable in the bin folder instead of where npm installs them globally worked for me.

I originally tried to use the location of it on the path:

``` shell
λ where jscs
C:\Users\buschs1\AppData\Roaming\npm\jscs
C:\Users\buschs1\AppData\Roaming\npm\jscs.cmd
```

But if I change it to point to the bin in the node_modules folder, it's fine:

``` json
"jscs_path": {
    "windows": "C:/Users/buschs1/AppData/Roaming/npm/node_modules/jscs/bin/jscs"
},
```

**Comment by brakmic** [comment] 2015-04-01 18:47
Hi @busches,

It works!

Many, many thanks. 

:+1:

**Comment by diegoesp** [comment] 2015-04-10 02:01
I also tested it and it works. I think this issue should be closed?
Thanks!

**Comment by elicwhite** [comment] 2015-04-10 02:08
Awesome, I'm glad you guys were able to come to a solution

@mrjoelkemp, do you have any ideas how we should fix this in the plugin reliably so other people don't have this problem in the future?

**Comment by mrjoelkemp** [comment] 2015-04-12 17:31
Haven't gotten around to trying the solution that omits the node path and shells out to `jscs` directly. If that works, then we don't have to deal with all of these different install locations – especially since the node_modules folder is within a username-specific directory.

**Comment by elicwhite** [comment] 2015-04-12 17:33
Gotcha, do you intend to give that a shot? Shall I leave this open until we resolve that? Or do you want to make a new issue specifically about that so that we can close this one?

**Comment by mrjoelkemp** [comment] 2015-04-12 18:22
Your call on how to handle the ticket. I won't be able to look into this until next weekend.

**Closed as completed** 2015-04-12 18:33 UTC
